cache:
  directories:
  - "$HOME/.m2"
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
script: "./build.sh"
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: Rgt/QK3vILA9L+ZFt/JMHXW2B5Cc4HlrgKRV+LKGagP4F3kNHZYg33sMuVSNYzZGBJSsgRBXXkEdB7TY2XVqLIk41bmsLCPV4YlpheTRBRBEvhVF0qSDy93fEZYo0SV2vWf9Yg+OU87B0Kh7Nn6AKPjU+vC3YVjAr4HpAmQ2F9hGAU+gFDubKYg00ABPXuzRr03yCTHQFsvzAxH903EQ90/kzXIZ09Ug13eCXlZgHi9P6t1GKsazVlXyYY7nzomJ6d+CNemzgJSt2tWI/ci4I7HJmBbTEpGxLXASfPvgXXbwqX66hfzoTkfJjn4z2CR6JoZZ4/afPW2l0xzfyXp0iFVoH2RuXGxx0dzx48tHkoPj5EZdBEW1pNArp+luqYL40rlPkT9OAdS4+fS0YQl41/RoAkkAg0dWxzcxTzPGdcQZLy0wAvDOUT3LWgIwqWHCdTAOZqFaxhY72ACthlcxmJV1vhbJh3dOLKA+hMQ9tq19+PKVAPkcBIU0n67QxIOSX+tByHzxmeojDaB+xK5xvcQfu2zM9P+DaPClrHrKRkSyuB6tEx4VCXtZGDMmagmXWDb3zNoWCLixIoTXrBC1ENUuSUAN43WJsI2vQWaOZvZuOlD9qvick3/gYB4o1n0/sOt2J0O5u9RiaSKdnk1o3mBMVdd8lq0N4E/Vc0BLQGM=
